# MongoDB Connection
spring:
  data:
    mongodb:
#      uri: mongodb://poom:poompwd1234@k8a805.p.ssafy.io:27017/poomdb
      host: k8a805.p.ssafy.io
      port: 27017
      authentication-database: admin
      database: testdb
      username: poom
      password: poompwd1234

  # Spring MVC 경로 매칭
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# swagger setting
springfox:
  documentation:
    swagger:
      v2:
        use-model-v3: false

server:
  servlet:
    contextPath : /api

# loggin level
logging:
  level:
    root: info  # TRACE  <  DEBUG  <  INFO  <  WARN  <  ERROR

oauth:
  kakao: cd2efe918e29d2852de282fb31320ac3


jwt:
  header: Authorization
  #HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
  #echo 'ssafy-8th-generation-class-8-team-5-jaewook-hyunju-sowon-taehyun-taesun-jinsoo-project-fighting-jwt-secret-secret-jwt-token'|base64
  secret: c3NhZnk4dGgtOGdlbmVyYXRpb24tY2xhc3MtdGVhbS05LWphZXdvb2stcnVubnktcnVubnktdGFlc3QtdGFlc3VuLXl1eW9uZy1wcm9qZWN0LWZpZ2h0aW5nLWp3dC1zZWNyZXQtc2VjcmV0LXNlY3JldC1qd3QtdG9rZW4=
  token-validity-in-minutes: 30